// AUTO-GENERATED by export_model_to_c.py — do not hand-edit.
// Regenerate this file whenever train_and_save.py is re-run with new data.
#ifndef MODEL_H
#define MODEL_H

// Feature order (must match training): ['soil_moisture', 'air_humidity', 'temperature', 'soil_deficit', 'crop_chili', 'crop_okra', 'crop_tomato']
// Known crops: ['tomato', 'chili', 'okra']
// Crop ideal soil thresholds (for the fail-safe rule): {'tomato': 58, 'chili': 45, 'okra': 50}

double score(double * input) {
    return -0.09098240480123718 + input[0] * -0.06121387957185912 + input[1] * 0.0036842432779452317 + input[2] * 0.08040503300418256 + input[3] * 0.09724347037911549 + input[4] * -0.2340155241154968 + input[5] * -0.270030907851819 + input[6] * 0.4149702339413418;
}


// sigmoid: turns the raw linear score into a 0..1 probability, same as
// sklearn's predict_proba() does internally for LogisticRegression.
double sigmoid(double x) {
  return 1.0 / (1.0 + exp(-x));
}

// Builds the exact feature vector the model expects, given raw sensor values
// and a crop name, then runs the model. Returns P(water) as a 0..1 probability.
double predictWaterProbability(double soil_moisture, double air_humidity,
                                double temperature, const char* crop_type) {
  double soil_deficit = 0;
  double crop_chili = 0, crop_okra = 0, crop_tomato = 0;

  if (strcmp(crop_type, "chili") == 0)       { soil_deficit = 45 - soil_moisture; crop_chili = 1; }
  else if (strcmp(crop_type, "okra") == 0)   { soil_deficit = 50 - soil_moisture; crop_okra = 1; }
  else if (strcmp(crop_type, "tomato") == 0) { soil_deficit = 58 - soil_moisture; crop_tomato = 1; }
  // unknown crop -> all dummy columns stay 0; caller should treat this as untrained territory

  double input[7] = { soil_moisture, air_humidity, temperature, soil_deficit,
                       crop_chili, crop_okra, crop_tomato };
  double raw_score = score(input);
  return sigmoid(raw_score);
}

#endif
