"""
Stage 06 TODO#2 — export the trained model to plain C so the ESP32 can run
inference itself, with no laptop server involved at all.

m2cgen converts sklearn's learned weights into a single arithmetic expression —
no sklearn, no Python, no server needed on the device. This is the same
LogisticRegression from train_and_save.py; only the *runtime* changes, not the model.
"""
import joblib
import m2cgen as m2c

model = joblib.load("model.pkl")
feature_cols = joblib.load("feature_cols.pkl")
known_crops = joblib.load("known_crops.pkl")
crop_ideal = joblib.load("crop_ideal.pkl")

# m2cgen gives us the raw linear score (before the sigmoid) as a C function body
raw_c_code = m2c.export_to_c(model)

print("Feature order the model expects (must match exactly, in this order):")
print(feature_cols)
print()
print("--- raw m2cgen output ---")
print(raw_c_code)

# Write an Arduino-ready header: same math, wrapped with sigmoid + feature
# construction so the .ino file can just call one function with raw sensor values.
header = f"""// AUTO-GENERATED by export_model_to_c.py — do not hand-edit.
// Regenerate this file whenever train_and_save.py is re-run with new data.
#ifndef MODEL_H
#define MODEL_H

// Feature order (must match training): {feature_cols}
// Known crops: {known_crops}
// Crop ideal soil thresholds (for the fail-safe rule): {crop_ideal}

{raw_c_code}

// sigmoid: turns the raw linear score into a 0..1 probability, same as
// sklearn's predict_proba() does internally for LogisticRegression.
double sigmoid(double x) {{
  return 1.0 / (1.0 + exp(-x));
}}

// Builds the exact feature vector the model expects, given raw sensor values
// and a crop name, then runs the model. Returns P(water) as a 0..1 probability.
double predictWaterProbability(double soil_moisture, double air_humidity,
                                double temperature, const char* crop_type) {{
  double soil_deficit = 0;
  double crop_chili = 0, crop_okra = 0, crop_tomato = 0;

  if (strcmp(crop_type, "chili") == 0)       {{ soil_deficit = 45 - soil_moisture; crop_chili = 1; }}
  else if (strcmp(crop_type, "okra") == 0)   {{ soil_deficit = 50 - soil_moisture; crop_okra = 1; }}
  else if (strcmp(crop_type, "tomato") == 0) {{ soil_deficit = 58 - soil_moisture; crop_tomato = 1; }}
  // unknown crop -> all dummy columns stay 0; caller should treat this as untrained territory

  double input[7] = {{ soil_moisture, air_humidity, temperature, soil_deficit,
                       crop_chili, crop_okra, crop_tomato }};
  double raw_score = score(input);
  return sigmoid(raw_score);
}}

#endif
"""

with open("model.h", "w") as f:
    f.write(header)

print("\nWrote model.h — copy this into your Arduino sketch folder.")
